<a href="https://colab.research.google.com/github/JagdeepMohanty/VALUE_ADDED_COURSE/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
print(f"pandas version : {pd.__version__}")

pandas version : 2.2.2

In [6]:
# crating series of cars
cars = pd.Series(['BMW','Toyota','Honda'])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [8]:
#creating colors
colors = pd.Series(['Red','Blue','White'])
colors

0      Red
1     Blue
2    White
dtype: object

In [10]:
#creating dataFrame of cars and colors
car_data = pd.DataFrame({'Car make':cars,'Color':colors})
car_data

  Car make  Color
0      BMW    Red
1   Toyota   Blue
2    Honda  White

In [14]:
Foods = pd.Series(['Chapati','daal','rice'])
dollars = pd.Series(['94.3','90','87.33'])
food_data = pd.DataFrame({'Foods':Foods,'Dollars':dollars})
food_data

     Foods Dollars
0  Chapati    94.3
1     daal      90
2     rice   87.33

In [27]:
import pandas as pd
import numpy as np

cars = pd.Series(np.random.choice(["BMW", "HONDA", "Nissan"], 11))
colors = pd.Series(np.random.choice(["red", "black", "blue", "white"], 11))
odometer = pd.Series(np.random.randint(1000, 200000, 11))
doors = pd.Series(np.random.choice([2, 3, 4, 5], 11))
price = pd.Series(np.random.randint(50000, 2000000, 11))

CAR_SLAES = {
    "Car": cars,
    "Color": colors,
    "Odometer": odometer,
    "Doors": doors,
    "Price": price
}

df = pd.DataFrame(CAR_SLAES )
df["Price"] = "$" + df["Price"].astype(str)
print(df)
df.to_csv("exported_car_sales.csv")

       Car  Color  Odometer  Doors     Price
0      BMW  white     10362      3    $67831
1   Nissan    red    153810      4   $574876
2      BMW  black    187607      5   $324195
3    HONDA   blue    179881      2  $1255786
4      BMW   blue    197607      3   $184283
5   Nissan  black     91310      2   $366817
6   Nissan  white    148519      5  $1732439
7      BMW  black    151823      3  $1852332
8    HONDA  white     51384      5  $1114567
9      BMW  black    184597      2   $169324
10     BMW  black     16577      3   $454671

In [28]:
#how to import csv files in code
car_sales = pd.read_csv("exported_car_sales.csv")
car_sales

    Unnamed: 0     Car  Color  Odometer  Doors     Price
0            0     BMW  white     10362      3    $67831
1            1  Nissan    red    153810      4   $574876
2            2     BMW  black    187607      5   $324195
3            3   HONDA   blue    179881      2  $1255786
4            4     BMW   blue    197607      3   $184283
5            5  Nissan  black     91310      2   $366817
6            6  Nissan  white    148519      5  $1732439
7            7     BMW  black    151823      3  $1852332
8            8   HONDA  white     51384      5  $1114567
9            9     BMW  black    184597      2   $169324
10          10     BMW  black     16577      3   $454671